### ISSUE TITLE
Refinement Needed in the Location Definition of the action_exec_timeout Field

### ISSUE THREAD

**Issue by Wuzhengyu97** [LLM-Evaluation-s-Always-Fatiguing/leaf-playground#41]
I have noticed that in the project, the action timeout duration is determined by the action_exec_time in SceneAgent. However, an agent might have multiple actions with differing timeout requirements. Under the current setup, this could lead to issues. To address this, I propose a solution: it would be more appropriate to place action_exec_time within ActionDefinition.

Below is my pull request regarding this solution. If you find it suitable, please consider merging it.

https://github.com/LLM-Evaluation-s-Always-Fatiguing/leaf-playground/pull/40

**Comment by PanQiWei** [comment]
@Wuzhengyu97 Thank you very much for point this out and provide the implementation! I close the issue for the PR is merged. Feel free to re-open this issue if you have any futher questions relevant to it.
